### PR TITLE
DESCRIPTION: add links to GitHub

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Comment by LTLA** [comment]
Is there some context behind this?

**Comment by mr-c** [comment]
Hello @LTLA 

Adding this information allows people looking at https://bioconductor.org/packages/release/bioc/html/scran.html to find this GitHub repository.

Also, Debian uses this information as well.

**Comment by LTLA** [comment]
Oops, forgot about this; merged now, thanks for the PR.

**Comment by mr-c** [comment]
No worries, @LTLA , you are welcome!

**Pull request merged**
